import mediapipe
import numpy as np
import rclpy

from . import config
from hand_publisher_interfaces.msg import HandPoints
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from rclpy.node import Node


class Landmark:
    x: float
    y: float
    z: float


class HandPointsNode(Node):

    def __init__(
        self,
        node_name: str = "hand_points_node",
        topic_image: str = "webcam",
        topic_hand_points: str = "hand_points",
    ):
        super().__init__(node_name)
        # subscribe to image from webcam
        self.subscription = self.create_subscription(
            msg_type=Image,
            topic=topic_image,
            callback=self.listener_callback,
            qos_profile=1,
        )
        self.subscription  # prevent unused variable warning
        # INIT
        self.bridge = CvBridge()
        self.declare_parameter("num_hands_per_src", 1)
        self.num_hands_per_src: list[str] = self.get_parameter("num_hands_per_src").value  # type: ignore
        self.mp_hands = mediapipe.solutions.hands  # type: ignore
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=self.num_hands_per_src,
            model_complexity=0,  # lighter model; higher => better & slower
            min_detection_confidence=0.6,
            min_tracking_confidence=0.5,
        )

        # publish hand points generated by mediapipe
        self.publisher_ = self.create_publisher(
            HandPoints, topic=topic_hand_points, qos_profile=10
        )

    def listener_callback(self, msg: Image):
        img_rgb = self.bridge.imgmsg_to_cv2(msg, desired_encoding="rgb8")
        results = self.hands.process(img_rgb)

        hand_points: list[list[Landmark]] = [[]]
        if results.multi_hand_landmarks:
            hand_marks = list(results.multi_hand_landmarks)
            # assert len(hand_marks) == config.NUM_HANDS_PER_SRC, f"{len(hand_marks)=}!={config.NUM_HANDS_PER_SRC=}"
            hand_points = [list(handLms.landmark) for handLms in hand_marks]
            landmarks = self.landmarks_to_handpoints(hand_points)
            # self.get_logger().debug('Hand points: "%s"' % str(len(landmarks)))
            msg_hand = HandPoints()
            msg_hand.points = landmarks
            self.publisher_.publish(msg_hand)
        else:
            self.get_logger().debug(
                'No hands! Image shape: "%s,%s"'
                % (msg.height, msg.width)
            )

    @staticmethod
    def landmarks_to_handpoints(hand_marks: list[list[Landmark]]) -> list[float]:
        assert len(hand_marks) == 1, f"{len(hand_marks)=}"
        # assume only one hand is detected per image => this should be set in the mediapipe settings
        hand = hand_marks[0]
        hand_points = sum(map(lambda x: [x.x, x.y, x.z], hand), start=[])
        return hand_points


def main(args=None):
    rclpy.init(args=args)

    hand_points_node = HandPointsNode()

    rclpy.spin(hand_points_node)

    hand_points_node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
